[project]
name = "pretix-flizpay-payment"
dynamic = ["version"]
description = "Enables payments via FLIZpay"
readme = "README.rst"
license = {text = "Apache"}
keywords = ["pretix"]
authors = [
    {name = "Christoph Walcher", email = "chris@wiomoc.de"},
]
maintainers = [
    {name = "Christoph Walcher", email = "chris@wiomoc.de"},
]

dependencies = [
]

[project.entry-points."pretix.plugin"]
pretix_flizpay = "pretix_flizpay:PretixPluginMeta"

[project.entry-points."distutils.commands"]
build = "pretix_plugin_build.build:CustomBuild"

[build-system]
requires = [
    "setuptools",
    "pretix-plugin-build",
]

[project.urls]
homepage = "https://github.com/wiomoc/pretix-flizpay-payment"
repository = "https://github.com/wiomoc/pretix-flizpay-payment"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "pretix_flizpay.__version__"}

[tool.setuptools.packages.find]
include = ["pretix*"]
namespaces = false
